### ISSUE TITLE
After using sharp-heif-lambda-layer not able to convert heic file to heif directly

### ISSUE THREAD

**Issue by abbey007** [Dobe-Solutions/sharp-heif-lambda-layer#1]
Hi there, 

Thanks for making this lambda layer which is very helpful to me reading heic data using sharp. 
But i have an issue, i am not able to directly convert the heic file to heif format using sharp . I am getting below error

Error: heifsave: Unsupported compression
    at Sharp.toBuffer (/opt/nodejs/node_modules/sharp/lib/output.js:161:17)
    at resizeImage (file:///var/task/index.mjs:394:6)
    at compressAndUpload (file:///var/task/index.mjs:276:30)
    at async Runtime.handler (file:///var/task/index.mjs:120:7)

I have also tried to convert the heic image to png or webp and then convert it to heif but same error

Looking forward for your help

Thanks
Abhijeet

**Comment by Cruaier** [comment]
Hi there,
As stated in the Readme the layer currently only supports decoding therefore the error.
I can have a look adding a flag to also build the libraries for encoding.

**Comment by abbey007** [comment]
Hi

Thanks for your reply. When can I expect
the new version for encoding. So I can able to convert heic directly to
heif files .

I am stuck on this step from weeks and tried multiple things

**Comment by Cruaier** [comment]
hi @abbey007,

I added some code to also support HEIF encoding. Please pay attention to the readme and some example code in the testing file (https://github.com/Dobe-Solutions/sharp-heif-lambda-layer/blob/main/test.mjs)
