### ISSUE TITLE
Include --platform in build command

### ISSUE THREAD

**Issue by brtinney** [Dobe-Solutions/sharp-heif-lambda-layer#2]
Thanks for this great resource -- I'd been trying to roll my own AVIF/HEIC support into [IPX](https://github.com/unjs/ipx) (for [Nuxt Image](https://github.com/nuxt/image) and the `sharp` stuff had been the last hurdle.

Building on an ARM Mac, because my Lambda function is running x86_64, I needed to add `--platform linux/amd64`, otherwise it built for/ran in `linux/arm64` and failed the tests at the end of the build.

Not sure if it is worth adding a flag to be able to build for either (since the Lambda function could theoretically use either platform), or just add the `--platform linux/amd64` hardcoded into the `run.sh`.

**Comment by Cruaier** [comment]
hi @brtinney - sorry for the late reply; missed the notification.
In the build script it already sets "--cpu=x64" which should be sufficient to cross-compile for x86_64 (see https://sharp.pixelplumbing.com/install#cross-platform).
I'll add a flag that targets ARM because you're right...you could also let it run under ARM.

**Comment by brtinney** [comment]
Sorry, I wasn't super clear. The `--platform` is for the Docker command in `run.sh` vs. the Dockerfile itself. Docker was building an ARM image, even though `sharp` was being compiled for x86_64, and I believe that was the issue.

**Comment by Cruaier** [comment]
Shouldn't it be irrelevant if the image is for ARM or x86? The generated output zip should work based on the compile options inside the container, or am I missing something?

Edit: Reading your first comment again; sure it will fail as the code is running under the wrong platform (the zip will still be fine though); I will add the fix.
