### ISSUE TITLE
Consider to use dav1d + rav1e for avif encoding & decoding

### ISSUE THREAD

**Issue by faradaytrs** [Dobe-Solutions/sharp-heif-lambda-layer#3]
These two seem to be much faster than libaom
Related: https://github.com/Dobe-Solutions/sharp-heif-lambda-layer/issues/3#issue-2404739338

**Comment by Cruaier** [comment]
Hi @faradaytrs do you have any benchmarks for that? It can be easily integrated into the build to use other decoders/encoders - if interested feel free to create a PR.

**Comment by faradaytrs** [comment]
> Hi @faradaytrs do you have any benchmarks for that? It can be easily integrated into the build to use other decoders/encoders - if interested feel free to create a PR.

I actually tried to build it, and it appeared to be slower, so i have lost interest.
AVIF is a big disappointment.  
i don't know why but no matter what encoders i try it's slow, well maybe it was the idea that it's not supposed to be fast, it focuses on compression, okay, I can accept it, BUT...
The size of the resulting picture is the SAME OR LARGER than the corresponding WebP, it just doesn't make sense.

**Comment by Cruaier** [comment]
There are cases where the image format is mandatory and therefore the need for encoders; fast, small output size or compatibility...there are many factors which can be important.

Closing the issue for now.
